routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HotelController@index'); 
Route::get('logout', 'Auth\LoginController@logout');

Route::group(['prefix' => 'dashboard'], function() {
    Route::view('/', 'dashboard/dashboard');
    Route::get('reservations/create/{id}', 'ReservationController@create');
    Route::resource('reservations', 'ReservationController')->except('create');
});
Auth::routes();
Route::resource('users', 'UserController');
Route::resource('trips', 'TripController');

app/Trip.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Trip extends Model
{
    protected $fillable = ['slug', 'title', 'description', 'start_date','end_date','location','price'];
}

app/Http/Controllers/TripController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Trip;
use Illuminate\Support\Str;

class TripController extends Controller
{
   /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $trip = Trip::all();
        return view('trip.index_trip', compact('trip'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('trip.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $storeData = $request->validate([
            'price' => 'required|numeric',
            'title' => 'required|max:255',
            'description' => 'required',
            'start_date' => 'required',
            'end_date' => 'required',
            'location' => 'required|max:255',
        ]);
        $slug = Str::slug($storeData['title'], '_');
        $storeData['slug'] =$slug;
        $trip = Trip::create($storeData);

        return redirect('/trips')->with('completed', 'Trip has been saved!');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $trip = Trip::findOrFail($id);
        return view('trip.edit', compact('trip'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $updateData = $request->validate([
            'price' => 'required|numeric',
            'title' => 'required|max:255',
            'description' => 'required',
            'start_date' => 'required',
            'end_date' => 'required',
            'location' => 'required|max:255',
        ]);
        $slug = Str::slug($updateData['title'], '_');
        $updateData['slug'] =$slug;
        Trip::whereId($id)->update($updateData);
        return redirect('/trips')->with('completed', 'Trip has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $trip = Trip::findOrFail($id);
        $trip->delete();

        return redirect('/trips')->with('completed', 'Trip has been deleted');
    }
}

resources/views/trip/create.blade.php
@extends('layout')

@section('content')

<style>
    .container {
      max-width: 450px;
    }
    .push-top {
      margin-top: 50px;
    }
</style>

<div class="card push-top">
  <div class="card-header">
    Add Trip
  </div>

  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('trips.store') }}">
          <div class="form-group">
              @csrf
              <label for="name">Title</label>
              <input type="text" class="form-control" name="title"/>
          </div>
          <div class="form-group">
              <label for="name">Description</label>
              <input type="textarea" class="form-control" name="description"/>
          </div>
          <div class="form-group">
              <label for="name">Start Date</label>
              <input type="date" class="form-control" name="start_date"/>
          </div>
          <div class="form-group">
              <label for="name">End Date</label>
              <input type="date" class="form-control" name="end_date"/>
          </div>
           <div class="form-group">
              <label for="name">Location</label>
              <input type="text" class="form-control" name="location"/>
          </div>
          <div class="form-group">
              <label for="name">Price</label>
              <input type="text" class="form-control" name="price"/>
          </div>
          <button type="submit" class="btn btn-block btn-danger">Create Trip</button>
      </form>
  </div>
</div>
@endsection

resources/views/trip/edit.blade.php
@extends('layout')

@section('content')

<style>
    .container {
      max-width: 450px;
    }
    .push-top {
      margin-top: 50px;
    }
</style>

<div class="card push-top">
  <div class="card-header">
    Edit & Update
  </div>

  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('trips.update', $trip->id) }}">
          <div class="form-group">
              @csrf
              @method('PATCH')
              <label for="name">Title</label>
              <input type="text" class="form-control" name="title" value="{{ $trip->title }}"/>
          </div>
          <div class="form-group">
              <label for="name">Description</label>
              <input type="textarea" class="form-control" name="description" value="{{ $trip->description }}"/>
          </div>
           <div class="form-group">
              <label for="name">Start Date</label>
              <input type="text" class="form-control" name="start_date" value="{{ $trip->start_date }}"/>
          </div> 
          <div class="form-group">
              <label for="name">End Date</label>
              <input type="text" class="form-control" name="end_date" value="{{ $trip->end_date }}"/>
          </div>
          <div class="form-group">
              <label for="name">Location</label>
              <input type="text" class="form-control" name="location" value="{{ $trip->location }}"/>
          </div>
          <div class="form-group">
              <label for="name">Price</label>
              <input type="text" class="form-control" name="price" value="{{ $trip->price }}"/>
          </div>
          <button type="submit" class="btn btn-block btn-danger">Update Trip</button>
      </form>
  </div>
</div>
@endsection

resources/views/trip/index_trip.blade.php
@extends('layout')

@section('content')

<style>
  .push-top {
    margin-top: 50px;
  }
</style>

<div class="push-top">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br/>
  @endif
  <table class="table">
    <thead>
        <tr class="table-warning">
          <td>Title</td>
          <td>Slug</td>
          <td>Description</td>
          <td>Start Date - End Date</td>
          <td>Location</td>
          <td>Price</td>
          <td class="text-center">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($trip as $trips)
        <tr>
            <td>{{$trips->title}}</td>
            <td>{{$trips->slug}}</td>
            <td>{!!strlen($trips->description) > 100 ? substr($trips->description,0,100) : $trips->description!!}</td>
            <td>{{$trips->start_date}} - {{$trips->end_date}}</td>
            <td>{{$trips->location}}</td>
            <td>{{$trips->price}}</td>
            <td class="text-center">
                <a href="{{ route('trips.edit', $trips->id)}}" class="btn btn-primary btn-sm">Edit</a>
                <form action="{{ route('trips.destroy', $trips->id)}}" method="post" style="display: inline-block">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                  </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
    <a href="{{ route('trips.create')}}" class="btn btn-primary btn-sm"">Create</a>
<div>
@endsection